version: '3.7'

services:

  frontend:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8760:3000
